name: CI CD Demo

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify HTML Exists
        run: |
          if [ -f index.html ]
          then
            echo "HTML file found"
          else
            echo "HTML file missing"
            exit 1
          fi

  deploy:

    needs: test

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload Website
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy Website
        id: deployment
        uses: actions/deploy-pages@v4
